#!/usr/bin/python3
import sys, os, pathlib
felix_ascii="""    |\\__/,|   (`\\
  _.|o o  |_   ) )
-(((---(((--------
"""
felix_path = os.path.join(os.getenv('HOME'), 'felix')
if not os.path.isdir(felix_path):
	os.makedirs(felix_path)
note_path = os.path.join(felix_path, 'note')
if sys.argv[1] == "take":
	if len(sys.argv) > 2:
		note_file = open(note_path, "a")
		note_file.write("".join(i + '\n' for i in sys.argv[2:]))
		print("Note prise !")
	else:
		print(felix_ascii + "Il n'y a pas de notes, Felix joue alors avec une pelotte.")
else:
	print(felix_ascii + "Felix n'a pas compris ce que vous lui demandez.")